version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
